# Iris dataset
The dataset is about three types of Iris flowers. The data has been collected of Iris viginica, Iris versicolor and Iris setosa.
## Dataset metadata
There is 150 samples has been recorded for the plants. Each plant has 50 samples. The samples described as:
* sepal length
* sepal width
* petal length
* petal width

The Iris versicolor and Iris viginica are very similar and hardly separatable from each other. On the otherhand Iris setosa can be easily separated from the other two. 

## Acquire the dataset
The data is available in csv format at UCI's or an easier way is to use sklearn datasets:

[UCI Repository](https://archive.ics.uci.edu/ml/datasets/Iris)

[Iris Dataset](http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data)

[Sklearn datasets](https://scikit-learn.org/stable/datasets/index.html)

In [10]:
#https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html#sklearn.datasets.load_iris
#Import the library
from sklearn.datasets import load_iris
#Load the dataset
iris = load_iris()
#Print the data to confirm its loaded
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [11]:
#Print the description
print(iris.DESCR)



Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

## Convert the dataset to pandas dataframe
_pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language._[Source](https://pandas.pydata.org/)

In [40]:
#Import pandas
import pandas as pd
import numpy as np
#Create array for the names
nt=['']*len(iris.target)
#Loop index
i=0
#Loop the targets
for t in iris.target:
    #Map the name into the new array
    nt[i]=iris.target_names[t]   
    #Increase the index
    i+=1 

#Create a dataframe from the loaded iris dataset
#The names of the species are in a separate array si it has to be concatenated to the data array
df = pd.DataFrame(np.c_[iris.data,nt], columns=iris.feature_names+['Species'])

In [43]:
#Print out the merged data
df

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm)  \
0                 5.1              3.5               1.4              0.2   
1                 4.9              3.0               1.4              0.2   
2                 4.7              3.2               1.3              0.2   
3                 4.6              3.1               1.5              0.2   
4                 5.0              3.6               1.4              0.2   
5                 5.4              3.9               1.7              0.4   
6                 4.6              3.4               1.4              0.3   
7                 5.0              3.4               1.5              0.2   
8                 4.4              2.9               1.4              0.2   
9                 4.9              3.1               1.5              0.1   
10                5.4              3.7               1.5              0.2   
11                4.8              3.4               1.6              0.2   
12                4.8              3.0               1.4              0.1   
13                4.3              3.0               1.1              0.1   
14                5.8              4.0               1.2              0.2   
15                5.7              4.4               1.5              0.4   
16                5.4              3.9               1.3              0.4   
17                5.1              3.5               1.4              0.3   
18                5.7              3.8               1.7              0.3   
19                5.1              3.8               1.5              0.3   
20                5.4              3.4               1.7              0.2   
21                5.1              3.7               1.5              0.4   
22                4.6              3.6               1.0              0.2   
23                5.1              3.3               1.7              0.5   
24                4.8              3.4               1.9              0.2   
25                5.0              3.0               1.6              0.2   
26                5.0              3.4               1.6              0.4   
27                5.2              3.5               1.5              0.2   
28                5.2              3.4               1.4              0.2   
29                4.7              3.2               1.6              0.2   
..                ...              ...               ...              ...   
120               6.9              3.2               5.7              2.3   
121               5.6              2.8               4.9              2.0   
122               7.7              2.8               6.7              2.0   
123               6.3              2.7               4.9              1.8   
124               6.7              3.3               5.7              2.1   
125               7.2              3.2               6.0              1.8   
126               6.2              2.8               4.8              1.8   
127               6.1              3.0               4.9              1.8   
128               6.4              2.8               5.6              2.1   
129               7.2              3.0               5.8              1.6   
130               7.4              2.8               6.1              1.9   
131               7.9              3.8               6.4              2.0   
132               6.4              2.8               5.6              2.2   
133               6.3              2.8               5.1              1.5   
134               6.1              2.6               5.6              1.4   
135               7.7              3.0               6.1              2.3   
136               6.3              3.4               5.6              2.4   
137               6.4              3.1               5.5              1.8   
138               6.0              3.0               4.8              1.8   
139               6.9              3.1               5.4              2.1   
